class AlarmQueryResult:
    def getAssociatedDate(self, uuid) -> None: ...
    def getDataSet(self) -> None: ...
    def getEvent(self, uuid) -> None: ...

class AlarmQueryResultImpl(AlarmQueryResult):
    def __init__(self, *args) -> None: ...
    def __iter__(self): ...
    def getAssociatedDate(self, uuid) -> None: ...
    def getDataSet(self) -> None: ...
    def getEvent(self, uuid) -> None: ...
