from typing import Any, Optional, Set, TypeVar, Union

from java.io import Closeable
from java.lang import Object
from java.util.function import Consumer

T = TypeVar("T")

class Channel(Closeable):
    def close(self) -> None: ...
    def isOpen(self) -> bool: ...

class SelectableChannel(Object, Closeable):
    def close(self) -> None: ...
    def blockingLock(self) -> Object: ...
    def configureBlocking(self) -> SelectableChannel: ...
    def isBlocking(self) -> bool: ...
    def isRegistered(self) -> bool: ...
    def keyFor(self, sel: Selector) -> SelectionKey: ...
    def provider(self) -> Object: ...
    def register(
        self, sel: Selector, ops: int, att: Optional[Object] = ...
    ) -> SelectionKey: ...
    def validOps(self) -> int: ...

class SelectionKey(Object):
    OP_ACCEPT: int
    OP_CONNECT: int
    OP_READ: int
    OP_WRITE: int
    def attach(self, ob: Object) -> Object: ...
    def attachment(self) -> Object: ...
    def cancel(self) -> None: ...
    def channel(self) -> SelectableChannel: ...
    def interestOps(self, ops: Optional[int] = ...) -> Union[int, SelectionKey]: ...
    def interestOpsAnd(self, ops: int) -> int: ...
    def interestOpsOr(self, ops: int) -> int: ...
    def isAcceptable(self) -> bool: ...
    def isConnectable(self) -> bool: ...
    def isReadable(self) -> bool: ...
    def isValid(self) -> bool: ...
    def isWriteable(self) -> bool: ...
    def readyOps(self) -> int: ...
    def selector(self) -> Selector: ...

class Selector(Object, Closeable):
    def close(self) -> None: ...
    def isOpen(self) -> bool: ...
    def keys(self) -> Set[SelectionKey]: ...
    @staticmethod
    def open() -> Selector: ...
    def provider(self) -> Object: ...
    def select(self, *args: Any) -> int: ...
    def selectedKeys(self) -> Set[SelectionKey]: ...
    def selectNow(self, action: Optional[Consumer] = ...) -> int: ...
    def wakeup(self) -> Selector: ...

class SocketChannel(SelectableChannel):
    def bind(self, local: Any) -> SocketChannel: ...
    def connect(self, remote: Any) -> bool: ...
    def finishConnect(self) -> bool: ...
    def getLocalAddress(self) -> Any: ...
    def getRemoteAddress(self) -> Any: ...
    def isConnected(self) -> bool: ...
    def isConnectionPending(self) -> bool: ...
    def open(self, remote: Optional[Any] = ...) -> SocketChannel: ...
    def read(self, *args: Any) -> Union[int, long]: ...
    def setOption(self, name: Any, value: T) -> SocketChannel: ...
    def shutdownInput(self) -> SocketChannel: ...
    def shutdownOutput(self) -> SocketChannel: ...
    def socket(self) -> Any: ...
    def write(self, *args: Any) -> Union[int, long]: ...
