from java.lang import Object

class LoggerEx(Object):
    def __init__(self) -> None: ...
    def getLogger(self) -> None: ...
    def getName(self) -> None: ...
    @staticmethod
    def log(*args) -> None: ...
