from typing import Union

from com.inductiveautomation.ignition.common import Path
from com.inductiveautomation.ignition.common.config import Property
from dev.thecesrom.helper.types import AnyStr

class TagPath(Path):
    def compareTo(self, that: TagPath) -> int: ...
    def getChildPath(self, arg: Union[Property, AnyStr]) -> TagPath: ...
    def getItemName(self) -> AnyStr: ...
    def getLastPathComponent(self) -> AnyStr: ...
    def getParentPath(self) -> Path: ...
    def getPathComponent(self, i: int) -> AnyStr: ...
    def getPathLength(self) -> int: ...
    def getProperty(self) -> Property: ...
    def getSource(self) -> AnyStr: ...
    def isAncestorOf(self, path: Path) -> bool: ...
    def toStringFull(self) -> AnyStr: ...
    def toStringPartial(self) -> AnyStr: ...
