from typing import Any

import java.lang
from dev.thecesrom.helper.types import AnyStr as AnyStr

class ClassNameResolver(java.lang.Object):
    def __init__(self) -> None: ...
    def addAlias(self, clazz: java.lang.Class, alias: AnyStr) -> None: ...
    def addDefaults(self) -> None: ...
    def addSearchPath(self, path: AnyStr) -> None: ...
    def classForName(self, name: AnyStr) -> java.lang.Class: ...
    def createBasic(self) -> ClassNameResolver: ...
    def getName(self, clazz: java.lang.Class) -> AnyStr: ...

class SerializationException(java.lang.Exception):
    def __init__(self, *args: Any) -> None: ...
