from typing import Any

from java.lang import Class
from java.lang import String as String

class TypeBuilder:
    def getBase(self) -> Class: ...
    def getDict(self, var1: Any) -> Any: ...
    def getDoc(self) -> String: ...
    def getIsBaseType(self) -> bool: ...
    def getName(self) -> String: ...
    def getTypeClass(self) -> Class: ...
