from typing import Any

from java.lang import IllegalArgumentException, String

class MathIllegalArgumentException(IllegalArgumentException):
    def __init__(self, pattern: String, *args: Any) -> None: ...
    def getContext(self) -> None: ...

class MathIllegalNumberException(MathIllegalArgumentException):
    INTEGER_ZERO: int
    def getArgument(self) -> None: ...

class DimensionMismatchException(MathIllegalNumberException):
    def __init__(self, *args: Any) -> None: ...
    def getDimension(self) -> None: ...
