from com.inductiveautomation.ignition.client.model import ClientContext
from java.lang import String
from javax.swing import JDesktopPane, JInternalFrame

class VisionDesktop(JDesktopPane):
    PRIMARY_DESKTOP_HANDLE: str
    def __init__(self, clientContext: ClientContext, handle: String = ...) -> None: ...
    def getAdapterContext(self) -> None: ...
    def getHandle(self) -> None: ...
    def getOpenedWindows(self) -> None: ...
    def getPath(self, window) -> None: ...
    def getScriptManager(self) -> None: ...
    def getWindow(self, arg) -> None: ...

class FPMIApp(VisionDesktop):
    TIMEZONE_CLIENT: str
    TIMEZONE_GATEWAY: str
    def getDefaultTimeZone(self) -> None: ...
    def getLastActivity(self) -> None: ...
    def shutdownDesigner(self) -> None: ...
    def startupDesigner(self, gatewayTimeZone) -> None: ...

class FPMIWindow(JInternalFrame):
    CACHE_ALWAYS: int
    CACHE_AUTO: int
    CACHE_NEVER: int
    DOCK_EAST: int
    DOCK_FLOAT: int
    DOCK_NORTH: int
    DOCK_SOUTH: int
    DOCK_WEST: int
    PARENT_WINDOW_NAME: str
    SHOW_ALWAYS: int
    SHOW_NEVER: int
    SHOW_MAXIMIZED: int
    name: String
    def __init__(self, name: String) -> None: ...
    def getPath(self): ...
    def getRootContainer(self) -> None: ...
