from java.lang import Object as Object
from java.lang import String as String
from java.util import EventObject as EventObject

class PropertyChangeEvent(EventObject):
    def __init__(
        self, source: Object, propertyName: String, oldValue: Object, newValue: Object
    ) -> None: ...
    def getNewValue(self) -> Object: ...
    def getOldValue(self) -> Object: ...
    def getPropagationId(self) -> Object: ...
    def setPropagationId(self, propagationId: Object) -> None: ...

class PropertyChangeListener:
    def propertyChange(self, evt: PropertyChangeEvent) -> None: ...
