from java.lang import String
from typing import List

def loadFromFile(filePath: String, projectName: String, mode: int) -> None: ...
def removeGroups(projectName: String, paths: List[String]) -> None: ...
