from typing import List, Union

Number = Union[float, int]

def geometricMean(values: List[Number]) -> float: ...
def kurtosis(values: List[Number]) -> float: ...
def max(values: List[Number]) -> float: ...
def mean(values: List[Number]) -> float: ...
def meanDifference(values1: List[Number], values2: List[Number]) -> float: ...
def median(values: List[Number]) -> float: ...
def min(values: List[Number]) -> float: ...
def mode(values: List[Number]) -> List[float]: ...
def normalize(values: List[Number]) -> List[float]: ...
def percentile(values: List[Number], percentile: float) -> float: ...
def populationVariance(values: List[Number]) -> float: ...
def product(values: List[Number]) -> float: ...
def skewness(values: List[Number]) -> float: ...
def standardDeviation(values: List[Number]) -> float: ...
def sum(values: List[Number]) -> float: ...
def sumDifference(values1: List[Number], values2: List[Number]) -> float: ...
def sumLog(values: List[Number]) -> float: ...
def sumSquares(values: List[Number]) -> float: ...
def variance(values: List[Number]) -> float: ...
