from typing import Any, Dict, Optional, Union

from com.inductiveautomation.factorypmi.application import FPMIWindow
from com.inductiveautomation.factorypmi.application.script.builtin import NavUtilities
from java.lang import String
from java.util import EventObject

def centerWindow(arg: Union[String, FPMIWindow]) -> None: ...
def closeParentWindow(event: EventObject) -> None: ...
def closeWindow(arg: Union[String, FPMIWindow]) -> None: ...
def desktop(handle: Optional[String] = ...) -> NavUtilities: ...
def getCurrentWindow() -> String: ...
def goBack() -> FPMIWindow: ...
def goForward() -> FPMIWindow: ...
def goHome() -> FPMIWindow: ...
def openWindow(
    path: String, params: Optional[Dict[String, Any]] = ...
) -> FPMIWindow: ...
def openWindowInstance(
    path: String, params: Optional[Dict[String, Any]] = ...
) -> FPMIWindow: ...
def swapTo(path: String, params: Optional[Dict[String, Any]] = ...) -> FPMIWindow: ...
def swapWindow(
    arg: Union[String, EventObject],
    swapToPath: String,
    params: Optional[Dict[String, Any]] = ...,
) -> FPMIWindow: ...
