from com.inductiveautomation.ignition.common.user import PyUser
from typing import Dict, List, Union

String = Union[str, unicode]

def addUsers(rosterName: String, users: List[PyUser]) -> None: ...
def createRoster(name: String, description: String) -> None: ...
def deleteRoster(rosterName: String) -> None: ...
def getRosters() -> Dict[String, List[String]]: ...
def removeUsers(rosterName: String, users: List[PyUser]) -> None: ...
