from typing import List, Sequence

from com.inductiveautomation.ignition.common import BasicDataset
from java.lang import String

def getAccounts() -> List[String]: ...
def getAccountsDataset() -> BasicDataset: ...
def getPhoneNumbers(accountName: String) -> Sequence: ...
def getPhoneNumbersDataset(accountName: String) -> BasicDataset: ...
def sendSms(
    accountName: String, fromNumber: String, toNumber: String, message: String
) -> None: ...
