class RequestWatcher:
    def block(self) -> None: ...
    def compose(self, requestWatchers) -> None: ...

class Request(RequestWatcher):
    def block(self) -> None: ...
    def cancel(self) -> None: ...
    def compose(self, requestWatchers) -> None: ...
    def get(self) -> None: ...
    def getError(self) -> None: ...
    def onError(self, func) -> None: ...
    def onSuccess(self, func) -> None: ...
