from typing import Any

from java.lang import Object

class Socket(Object):
    def __init__(self, *args) -> None: ...
    def bind(self, bindpoint) -> None: ...
    def close(self) -> None: ...
    def connect(self, endpoint, timeout) -> None: ...
    def getChannel(self) -> None: ...
    def getInetAddress(self) -> None: ...
    def getInputStream(self) -> None: ...
    def getKeepAlive(self) -> None: ...
    def getLocalAddress(self) -> None: ...
    def getLocalPort(self) -> None: ...
    def getLocalSocketAddress(self) -> None: ...
    def getOOBInline(self) -> None: ...
    def getOption(self, name) -> None: ...
    def getOutputStream(self) -> None: ...
    def getPort(self) -> None: ...
    def getReceiveBufferSize(self) -> None: ...
    def getRemoteSocketAddress(self) -> None: ...
    def getReuseAddress(self) -> None: ...
    def getSendBufferSize(self) -> None: ...
    def getSoLinger(self) -> None: ...
    def getSoTimeout(self) -> None: ...
    def getTcpNoDelay(self) -> None: ...
    def getTrafficClass(self) -> None: ...
    def isBound(self) -> None: ...
    def isClosed(self) -> None: ...
    def isConnected(self) -> None: ...
    def isInputShutdown(self) -> None: ...
    def isOutputShutdown(self) -> None: ...
    def sendUrgentData(self, data) -> None: ...
    def setKeepAlive(self, on) -> None: ...
    def setOOBInline(self, on) -> None: ...
    def setOption(self, name, value) -> None: ...
    def setPerformancePreferences(self, connectionTime, latency, bandwidth) -> None: ...
    def setReceiveBufferSize(self, size) -> None: ...
    def setReuseAddress(self, on) -> None: ...
    def setSendBufferSize(self, size) -> None: ...
    @staticmethod
    def setSocketImplFactory(fac) -> None: ...
    def setSoLinger(self, on, linger) -> None: ...
    def setSoTimeout(self, timeout) -> None: ...
    def setTcpNoDelay(self, on) -> None: ...
    def setTrafficClass(self, tc) -> None: ...
    def shutdownInput(self) -> None: ...
    def shutdownOutput(self) -> None: ...
    def supportedOptions(self) -> None: ...

class SocketAddress(Object):
    def __init__(self) -> None: ...

class InetSocketAddress(SocketAddress):
    def __init__(self, *args: Any) -> None: ...
    @staticmethod
    def createUnresolved(host, port): ...
    def getAddress(self) -> None: ...
    def getHostname(self) -> None: ...
    def getHostString(self) -> None: ...
    def getPort(self) -> None: ...
    def isUnresolved(self) -> None: ...
