from java.lang import Object as Object
from java.lang import String as String
from javax.security.auth import Subject

class Principal:
    def equals(self, another: Object) -> bool: ...
    def getName(self) -> String: ...
    def hashCode(self) -> int: ...
    def implies(self, subject: Subject) -> bool: ...
    def toString(self) -> String: ...
